### ISSUE TITLE
equations not shown upon reload

### ISSUE THREAD

**Issue by PengjuYan** [YakovL/TiddlyWiki_TwFormulaPlugin#1] opened 2024-03-20 03:41 UTC
Hi Yakov,

I couldn't wait to try the release version of this amazing plugin!

I found it seems still doesn't work as expected in my case (like what 0.5.9 behaves). The equations in a default tiddler (`DefaultTiddlers`) won't show when the TWC file is opened/reloaded. When I closed the tiddler and reopen it again, the equations show.

Reproduction:

1. macOS 14.3.1
2. Firefox 124.0
3. TiddlyWiki Classic 2.10.1
4. TwFormulaePlugin 0.7.5
5. SystemSettings
```
txtMathLib: KaTeX
txtMathLibPath: jsLibs/KaTeX/
```
7. Relative KaTeX JavaScript library path: `jsLibs/KaTeX`

Here is the snapshots:

1. My tiddler:
```
<<option txtMathLib>>
<<option txtMathLibPath>>

\[c^2=a^2+b^2\]
```
2. UI rendering upon file reloading:
![20240320-113822](https://github.com/YakovL/TiddlyWiki_TwFormulaPlugin/assets/13349414/cdfb3e24-c008-495f-baa7-6d883507c4ac)
3. UI rendering after tiddler being closed and reopened:
![20240320-113452](https://github.com/YakovL/TiddlyWiki_TwFormulaPlugin/assets/13349414/8bbf89bf-7bf1-4485-8e19-be62c2708ca9)

Pengju

**Comment by YakovL** [comment] 2024-03-25 12:22
Hi @PengjuYan, thanks for pointing, I can reproduce the issue in Firefox (but not in Chrome, so this is something browser-specific). I'll research the issue and let you know once I fix it.

**Comment by PengjuYan** [comment] 2024-03-27 05:16
Many thanks @YakovL. You can't imagine how I was struggled using the _ancient_ MathSVGPlugin, where many KaTeX features were missing. Now I can write almost anything a normal KaTeX engine allows. Looking forward to your update.

**Comment by YakovL** [comment] 2024-04-02 07:51
Hi @PengjuYan, strangely enough, I can no longer reporoduce the issue in FF (neither when a TW is opened via file:// nor on localhost, via MTS). Can you may be provide a TW file that reproduces the issue?

**Comment by YakovL** [comment] 2024-04-02 07:55
Ah, nevermind, I've reproduced it again. It only happens in Firefox (not Chrome) _when a local folder for a lib is used (not a CDN)_

PS Nope, local folder has nothing to do with this, looks like the problem takes place _on the first load of the lib_ from any source (so it's not cached). After the problem stopped reproducing with the local folder, I've tried to open the same TW in a private window, and reproduced it once again. Reloading in such a window doesn't reproduce it, but **closing a private window, opening it again and the TW in it seems to reproduce the problem each time**.

**Comment by PengjuYan** [comment] 2024-04-02 12:59
Just made an empty TWC file for you to reproduce and was about to upload it ...

Not sure I catch what you said, but my situation IS with _local folder libraries_.

**Comment by PengjuYan** [comment] 2024-04-02 13:02
Anyway, let me upload it. In my case, it reproduces whenever I reopen this TWC file in a normal FF window.

[formulae test.html.zip](https://github.com/YakovL/TiddlyWiki_TwFormulaPlugin/files/14836951/formulae.test.html.zip)

**Comment by YakovL** [comment] 2024-04-06 11:31
Thanks @PengjuYan , the uploaded example really helped with reproducing the issue. Check 0.7.6: should work fine now

**Comment by PengjuYan** [comment] 2024-04-07 01:38
> Thanks @PengjuYan , the uploaded example really helped with reproducing the issue. Check 0.7.6: should work fine now

Thanks a lot. I works perfect now.

**Closed as completed** 2024-04-07 01:43 UTC
